### ISSUE TITLE
Add Tutorial Set Up Notes

### ISSUE THREAD

**Issue by marabout2015** [Microsoft/AKSDeploymentTutorial#18]
Add notes that tell people how to themselves up for running the tutorial notebooks. Examples include:

- Set up a virtual environment with conda env create --file environment.yml

Should there be notes for docker set up?

**Comment by msalvaris** [comment]
I like the idea of having both virtual env and docker setup

**Comment by marabout2015** [comment]
Re: docker setup, Fidan mentioned being part of the docker group being needed to run the notebooks. Could you say more about that?

**Comment by fboylu** [comment]
See here https://docs.docker.com/install/linux/linux-postinstall/

**Comment by msalvaris** [comment]
Addressed in #30
