### ISSUE TITLE
Add instructions on operationalizing in commercial environment

### ISSUE THREAD

**Issue by grecoe** [Microsoft/AKSDeploymentTutorial#23]
While this is an open topic, place holder here on informing users that:

1. How to implement a metrics mechanism to understand API usage (current thought is App Insights).
2. How to add security to the endpoint 
3. Scaling to meet demand

Current thought is that these will be covered in some other repo (maybe related to this one, maybe not). Topic at least needs to be discussed that the end result is not viable for commercial use as is (for most enterprise use cases). Final destination for this content to be decided in September.

(Topic valid for all Real Time Endpoints)

**Comment by msalvaris** [comment]
Yep, we can add caveat to the readme along those lines. Then at a later date when those instructions are available link to them.
