### ISSUE TITLE
Notebook 03_testlocally

### ISSUE THREAD

**Issue by jaymathe** [Microsoft/AKSDeploymentTutorial#27]
In my case, it took around 4-5 minutes to spin up the application. Perhaps the time varies by the type of VM used.

**Comment by marabout2015** [comment]
This may be a different issue than what Jaya experienced. At times, when I run this notebook, it can get stuck in the section at the bottom that looks to compute average time information for multiple images. I've had to restart the kernel, run everything again, and then it works. Fidan, who suggested the workaround, said she had similar problems. Now, a similar problem occurs with the corresponding notebook in MLAKSDeployment (notebook 04).

**Comment by msalvaris** [comment]
OK, will try to reproduce. Thanks

**Comment by jaymathe** [comment]
Interestingly I just re-ran the notebook today and it ran in less than a minute. There seems to be some variability in the amount of time required for this step.

**Comment by msalvaris** [comment]
OK, if it is not persistent or reproducible then it will be hard to address. I will leave this here but I will attribute this to transient behaviour and possible resource contention on the VM running things.

**Comment by msalvaris** [comment]
@marabout2015 If you think your issue is different please open another issue
