### ISSUE TITLE
Issue with image_name

### ISSUE THREAD

**Issue by jaymathe** [Microsoft/AKSDeploymentTutorial#29]
For some reason I had an issue with this cat command in )4_DeployOnAKS, it seemed to add additional quotations and they messed up the name and caused parsing error later
%dotenv
image_name = os.getenv('docker_login') + os.getenv('image_repo')

**Comment by msalvaris** [comment]
@jaymathe Could you post links to the notebooks you ran? Either upload to a repo or blob? It is hard to diagnose without that information

**Comment by jaymathe** [comment]
Sure! I have the notebooks uploaded onto Teams

**Comment by msalvaris** [comment]
The error comes from here:
```bash
%%writefile .env
# This cell is tagged `parameters`
# Please modify the values below as you see fit

# Your docker login and image repository name
docker_login = "jayamathew"
image_repo = "/kerastf-gpu"
````

You need to define them without quotes. When you use writefile it is no longer python so the quotes are not necessary.  That is where your extra quotes stem from. The writefile way of creating .env files isn't what I originally envisioned but we can address that later.
