### ISSUE TITLE
No module named 'tensorflow'

### ISSUE THREAD

**Issue by rahulai** [Microsoft/AKSDeploymentTutorial#44]
After following the prereqs, when I launch the first notebook for Tensorflow, I get the following error - _ImportError: No module named 'tensorflow'._ 
I DID select the correct kernel (Microsoft ML Server Python 3.5). 
This is on a fresh Ubuntu DSVM. 
Cursory internet search suggests that this may be avoided by adding the --ignore-installed after the pip command for tensorflow installation but I am not sure if this is the correct solution or a workaround that may cause additional problems later. ( https://stackoverflow.com/questions/42244198/importerror-no-module-named-tensorflow ). Also I don't know how to do this in Conda.

**Comment by msalvaris** [comment]
Thanks @rahulai.  We have an enviroment.yml file for each of the frameworks. We suggest you create the conda environment based on that file as mentioned in the readme.
